<a href="https://colab.research.google.com/github/A-R-TAQI/ml_lab/blob/main/rand_forest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
from sklearn.ensemble import RandomForestClassifier
import pandas as pd

In [19]:
df=pd.read_csv('/content/drive/MyDrive/ml_lab/play_tennis.csv')

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
df.head()

  day   outlook  temp humidity    wind play
0  D1     Sunny   Hot     High    Weak   No
1  D2     Sunny   Hot     High  Strong   No
2  D3  Overcast   Hot     High    Weak  Yes
3  D4      Rain  Mild     High    Weak  Yes
4  D5      Rain  Cool   Normal    Weak  Yes

In [22]:
y=df['play']

In [23]:
x = df.drop(['play'], axis =1)

In [24]:
x

    day   outlook  temp humidity    wind
0    D1     Sunny   Hot     High    Weak
1    D2     Sunny   Hot     High  Strong
2    D3  Overcast   Hot     High    Weak
3    D4      Rain  Mild     High    Weak
4    D5      Rain  Cool   Normal    Weak
5    D6      Rain  Cool   Normal  Strong
6    D7  Overcast  Cool   Normal  Strong
7    D8     Sunny  Mild     High    Weak
8    D9     Sunny  Cool   Normal    Weak
9   D10      Rain  Mild   Normal    Weak
10  D11     Sunny  Mild   Normal  Strong
11  D12  Overcast  Mild     High  Strong
12  D13  Overcast   Hot   Normal    Weak
13  D14      Rain  Mild     High  Strong

In [25]:
x1 = x.drop('day',axis=1)

In [26]:
x1

     outlook  temp humidity    wind
0      Sunny   Hot     High    Weak
1      Sunny   Hot     High  Strong
2   Overcast   Hot     High    Weak
3       Rain  Mild     High    Weak
4       Rain  Cool   Normal    Weak
5       Rain  Cool   Normal  Strong
6   Overcast  Cool   Normal  Strong
7      Sunny  Mild     High    Weak
8      Sunny  Cool   Normal    Weak
9       Rain  Mild   Normal    Weak
10     Sunny  Mild   Normal  Strong
11  Overcast  Mild     High  Strong
12  Overcast   Hot   Normal    Weak
13      Rain  Mild     High  Strong

In [27]:
x1=pd.get_dummies(x1,columns=['outlook'])
x1=pd.get_dummies(x1,columns=['temp'])
x1=pd.get_dummies(x1,columns=['humidity'])
x1=pd.get_dummies(x1,columns=['wind'])

In [28]:
x1

,outlook_Overcast,outlook_Rain,outlook_Sunny,temp_Cool,temp_Hot,temp_Mild,humidity_High,humidity_Normal,wind_Strong,wind_Weak
0,0,0,1,0,1,0,1,0,0,1
1,0,0,1,0,1,0,1,0,1,0
2,1,0,0,0,1,0,1,0,0,1
3,0,1,0,0,0,1,1,0,0,1
4,0,1,0,1,0,0,0,1,0,1
5,0,1,0,1,0,0,0,1,1,0
6,1,0,0,1,0,0,0,1,1,0
7,0,0,1,0,0,1,1,0,0,1
8,0,0,1,1,0,0,0,1,0,1
9,0,1,0,0,0,1,0,1,0,1
10,0,0,1,0,0,1,0,1,1,0
11,1,0,0,0,0,1,1,0,1,0
12,1,0,0,0,1,0,0,1,0,1
13,0,1,0,0,0,1,1,0,1,0

In [29]:
y

0      No
1      No
2     Yes
3     Yes
4     Yes
5      No
6     Yes
7      No
8     Yes
9     Yes
10    Yes
11    Yes
12    Yes
13     No
Name: play, dtype: object

In [30]:
from sklearn.ensemble import RandomForestClassifier
rnd_clf = RandomForestClassifier(n_estimators=500, max_leaf_nodes=16,n_jobs=-1, random_state=42)
rnd_clf.fit(x1,y)

RandomForestClassifier(max_leaf_nodes=16, n_estimators=500, n_jobs=-1,
                       random_state=42)

In [31]:
y_pred = rnd_clf.predict(x1)
y_pred

array(['No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes',
       'Yes', 'Yes', 'Yes', 'No'], dtype=object)

In [32]:
from sklearn.metrics import accuracy_score
accuracy_score(y,y_pred)

1.0